-- Additional research families; shared by unlock assignment, technologies and the guide.
return {
  {name="pressing", prerequisites={"materials"}, icon="y-heat-form-press",
    trigger={type="craft-item",item="y-crush-yres1",count=50},
    recipes={"y-heat-form-press","y-smelt-crush-res1","y-smelt-crush-res2"}},
  {name="compacting", prerequisites={"pressing"}, icon="y-unicomp-raw",
    trigger={type="craft-item",item="y-refined-yres1",count=30},
    recipes={"y-unicomp-raw","y-raw-fuelnium"}},
  {name="alloying", prerequisites={"pressing"}, icon="y-orange-stuff",
    trigger={type="craft-item",item="y-crush-yres2",count=50},
    recipes={"y-mixing-rich","y-orange-stuff"}},
  {name="structures", prerequisites={"compacting"}, icon="y_structure_element",
    trigger={type="craft-item",item="y-unicomp-raw",count=20},
    recipes={"y_structure_element","y_structure_vessel","y-bluegear"}},
  {name="electronics", prerequisites={"alloying"}, icon="y-chip-1",
    trigger={type="craft-item",item="y-orange-stuff",count=30},
    recipes={"y-conductive-wire-1","y_chip_plate","y-chip-1"}},
  {name="fuel-processing", prerequisites={"compacting"}, icon="y-fuel-reactor",
    trigger={type="craft-item",item="y-raw-fuelnium",count=10},
    recipes={"y-fuel-reactor"}},
  {name="basic-factory", prerequisites={"structures","electronics"}, icon="ye_fassembly1",
    trigger={type="craft-item",item="y-chip-1",count=20},
    recipes={"y-basic-t1-mf","ye_fassembly1"}},
  {name="industrial-science", prerequisites={"basic-factory","fuel-processing"}, icon="quinityn-research-data",
    trigger={type="craft-item",item="ye_fassembly1",count=1},recipes={}},
  {name="excavation", prerequisites={"industrial-science"}, count=50, icon="y-underground-drill",
    recipes={"y-mining-drill-e2","y-underground-drill","y-digfdirt"}},
  {name="washing", prerequisites={"industrial-science"}, count=40, icon="y-dirtwasher",
    recipes={"y-dirtwasher","y-filtering-dust","y-press-richdust","y-pressed_dry_mud","y-pure-copper","y-pure-iron","y-release-cwater","y-wash-dirt","y-wash-special","y-refined-copper","y-refined-iron","y_slag_brick","y_slag_brick_burn","y_slag_granulate","y_steinmehl","y_tile_slagbricks","y_tile_slagfilled","y_tile_slagpattern"}},
  {name="tooling", prerequisites={"excavation","washing"}, count=80, icon="y_toolhead",
    recipes={"y_toolhead","y_drillhead","y-crush-blue_whead","y-crush-green_whead","y_pure_copper_wtool","y_pure_iron_wtool","y-digfdirt2"}},
  {name="advanced-machining", prerequisites={"industrial-science"}, count=80, icon="y_crusher2",
    recipes={"y_crusher2","y_formpress2"}},
  {name="advanced-components", prerequisites={"oil-processing"}, count=100, icon="y-chip-2",
    recipes={"y-basic-t2-mf","y-chip-2","y-conductive-coil-1","y_structure_electric","y_dotzetron","y_block_cold","y_block_heat","yi_magnetron"}},
  {name="maintenance", prerequisites={"tooling","advanced-machining","advanced-components","logistics"}, count=100, icon="y_maintance_workshop",
    recipes={"y_maintance_workshop","y_drillhead_repair","y_toolhead_repair"}},
  {name="energy-storage", prerequisites={"power","washing","advanced-components"}, count=100, icon="y-accumulator-m",
    recipes={"y-battery-single-use1","y-battery-single-use2","y-battery-single-use3","y-battery-rip1","y_blocked_capa","y-accumulator-m","y-accumulator-b","y-ups-flywheel-b","y_compensator_25"}},
  {name="advanced-storage", prerequisites={"energy-storage","quantum"}, count=160, icon="y-accumulator-m-t2",
    recipes={"y-accumulator-m-t2","y-accumulator-b-t2"}},
  {name="reactors", prerequisites={"refining","advanced-components","defense","advanced-generation"}, count=160, icon="y-obninsk-reactor",
    recipes={"y_moxmixer","y_mox1mixed","y_reactor_mox1","y_mox1fuel","y_reactor_mf1","y-obninsk-reactor","y-rare-wall-adv"}},
  {name="quantum-power", prerequisites={"advanced-storage","reactors"}, count=250, icon="y-accumulator-crystal-m",
    recipes={"y-accumulator-b-tx","y-accumulator-crystal-m","y_alien_solar2","y-substation-h","y-obninsk-turbine","y_mox2mixed","y_reactor_mox2","y_mox2fuel","y_mox2fuelsplited"}},
  {name="fluid-handling", prerequisites={"engines"}, count=80, icon="ye_canmachine",
    recipes={"ye_canmachine","ye_canister","ye_sealing","ye_icemaker","ye_ice_container_empty","ye_ice_container_filled","ye_can_blood_empty","ye_can_blood_fill","ye_can_co_empty","ye_can_eth_empty","ye_can_ho_empty","ye_can_lub_empty","ye_can_mf_empty","ye_can_petrol_empty","ye_can_sa_empty","ye_can_slurry_empty","ye_can_uc_empty","ye_can_veg_empty"}},
  {name="advanced-factories", prerequisites={"engines","advanced-machining"}, count=140, icon="ye_fassembly2",
    recipes={"yie_science_blue_gen","ye_science_blue","ye_fassembly2","ye_fassembly_sp"}},
  {name="advanced-engines", prerequisites={"advanced-factories","advanced-components"}, count=180, icon="ye_gasmotor",
    recipes={"y-ffe","ye_gasmotor","y-mf2a","y-mf2b","y-mf2c","y-mf2d","y-mf2e","ye_emotor_m","ye_motorm_mf","ye_mfheatmotor_m","ye_mf_mfheatmotor_m","ye_sturbine","ye_steam2mf","ye_steam3mf","ye_tfmw_generator-s","ye_tfmw_turbine-s","ye_overheater","ye_makesteam"}},
  {name="advanced-transmission", prerequisites={"engines","advanced-components"}, count=120, icon="ye_tranport_tube_green",
    recipes={"ye_tranport_tube_green","ye_tranport_tube_green_splitter","ye_tranport_tube_green_underground","y-mftrans-shaft-red","y-mftrans-shaft-ground-red"}},
  {name="crystal-processing", prerequisites={"refining","washing"}, count=150, icon="y_crystalizer",
    recipes={"y_crystalizer","y_mixer_emu","y_hppump","y_emulsion","y_richemulsion","y_crystal_dust","y_chunks1","y_chunks2","y_trockner"}},
  {name="husbandry", prerequisites={"agriculture","advanced-factories","fluid-handling"}, count=160, icon="ye_meatfarm",
    recipes={"ye_meatfarm","ye_pool","ye_dnasplicer","ye_dna_animal0","ye_dna_animal1","ye_grow_animal_a","ye_grow_fish1","ye_pool_slurry","ye_cooking_meat","yie_bloodfrommeat","ye_fish3","ye_fish4","ye_futtermittel_c","ye_futtermittel_d","ye_smoked_fish","ye_smoked_meat","ye_smoker"}},
  {name="genetics", prerequisites={"husbandry"}, count=200, icon="ye_krakon1",
    recipes={"ye_dna_animal2","ye_grow_animal2","ye_dna_plant0","ye_dna_plant1","ye_dna_plant3","ye_grow_plant1"}},
  {name="advanced-genetics", prerequisites={"genetics","quantum"}, count=250, icon="ye_krakon2",
    recipes={"ye_dna_animal3","ye_grow_animal3","ye_grow_animal3fast","ye_dna_plant4","ye_grow_plant2","ye_fish2"}},
  {name="industrial-biology", prerequisites={"advanced-genetics"}, count=300, icon="ye_krakon3",
    recipes={"ye_dna_animal4","ye_grow_animal4","yie_pureiron"}},
  {name="advanced-logistics", prerequisites={"logistics","quantum"}, count=160, icon="y-inserter-smart",
    recipes={"y-inserter-smart","y-inserter-smart-long","y_inserter_diagonal","y_inserter_evade_shortL","y_inserter_evade_shortR","y_inserter_smart_LL","y_inserter_smart_RR","y_inserter_smart_leftR2","y_inserter_smart_rightR2"}},
  {name="robotics", prerequisites={"logistics","quantum","energy-storage"}, count=180, icon="yi_roboport",
    recipes={"yi_construction-robot","yi_logistic-robot","yi_roboport","j_yi_roboport1"}},
  {name="advanced-robotics", prerequisites={"robotics"}, count=240, icon="j_logistic2-robot",
    recipes={"j_construction2-robot","j_logistic2-robot"}},
  {name="advanced-defense", prerequisites={"defense","advanced-components","energy-storage"}, count=160, icon="y_turret_plasma",
    recipes={"y_turret_gun2f12","y_turret_laser22f12","y_turret_plasma","y_turret_flame","y-wall-forcefield","y_wall22_hardic","y_ammo_flame","y_ammo_plasma","yi_artillery_shell","yi_mine_impact","yi_mine_plasma"}},
  {name="powered-armor", prerequisites={"trade","advanced-defense","energy-storage"}, count=200, icon="yi_armor_gray",
    recipes={"yi_armor_gray","yi_equip_battery_a","yi_equip_legs_a","yi_equip_shield_a","yi_ammo_energie","yi_lasergun","yi_minigun","yi_equip_roboport","yi_pld_equipment"}},
  {name="armor-2", prerequisites={"powered-armor","advanced-storage"}, count=240, icon="yi_armor_red",
    recipes={"yi_armor_red","yi_equip_shield_b"}},
  {name="armor-3", prerequisites={"armor-2"}, count=300, icon="yi_armor_gold",
    recipes={"yi_armor_gold"}},
  {name="walker-1", prerequisites={"armor-3","mastery"}, count=400, icon="yi_walker_a",
    recipes={"yi_walker_a","yi_equip_generator_a"}},
  {name="walker-2", prerequisites={"walker-1"}, count=500, icon="yi_walker_c",
    recipes={"yi_walker_c"}},
  {name="modules", prerequisites={"advanced-components"}, count=100, icon="y-speed-module-1",
    recipes={"y-speed-module-1","y-green-module-1","y-pink-module-1"}},
  {name="advanced-modules", prerequisites={"modules","quantum"}, count=180, icon="y-speed-module-2",
    recipes={"y-speed-module-2","y-green-module-2","y-pink-module-2"}},
  {name="quantum-modules", prerequisites={"advanced-modules"}, count=250, icon="y-pink-module-3",
    recipes={"y-pink-module-3","y-quality-module-1","y_modul_red2","y_modul_science"}},
  {name="packaging", prerequisites={"agriculture","fluid-handling"}, count=120, icon="ye_package_empty",
    recipes={"ye_package_empty","ye_buechse_empty","ye_package_c_meat","ye_package_carni","ye_package_fish1","ye_package_fish2","ye_package_omtrinit","ye_package_organic","ye_package_r_meat","ye_package_spliced_cells","ye_package_substratin","ye_package_verotin","ye_buechse_blau","ye_buechse_braun","ye_buechse_gelb","ye_buechse_rosa","ye_buechse_white"}},
  {name="advanced-generation", prerequisites={"power","advanced-components","engines","refining"}, count=140, icon="y-boiler-iv",
    recipes={"y-boiler-iv","y-beg","y-heg","y-meg-s","y-seg","y-water-gen-e"}},
  {name="plant-infrastructure", prerequisites={"power","advanced-components"}, count=80, icon="y-tank-4500",
    recipes={"y-pipe-ec","y-pipe-h","y-pipe-hc","y-pipe-to-ground-ec","y-pipe-to-ground-hc","y-pipe-v","y-powerlamp","y-substation-m","y-tank-1000","y-tank-4500","y-tank-8000","y-tinylamp","y_lampe_44basement_a","y_lampe_44basement_b","y_lampe_66basement","y_lampe_corner","y_lampe_neotix","y_lampe_yuoki","y_signal_pole","yi-monument1","yi_pipe_green","yi_pipe_underground_green"}},
}
